branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: hurleyisms
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
