branch-defaults:
  master:
    environment: hurleyisms-dp
    group_suffix: null
global:
  application_name: hurleyisms
  default_ec2_keyname: TestKeyPair
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
